const weatherData = [
  {
    main: 'Clouds',
    description: 'overcast clouds',
    icon: '04n',
    temp: 2.12,
    feels_like: -3.06,
    temp_min: 2.12,
    temp_max: 2.12,
    location: 'Ukraine',
  },
  {
    main: 'Clouds',
    description: 'overcast clouds',
    icon: '04d',
    temp: 11.69,
    feels_like: 11.32,
    temp_min: 11.14,
    temp_max: 11.69,
    location: 'Spain',
  },
  {
    main: 'Clear',
    description: 'clear sky',
    icon: '01d',
    temp: 4.07,
    feels_like: 3.11,
    temp_min: 2.84,
    temp_max: 5.75,
    location: 'Italy',
  },

  {
    main: 'Clouds',
    description: 'scattered clouds',
    icon: '03d',
    temp: -1.26,
    feels_like: -1.26,
    temp_min: -6.42,
    temp_max: -0.18,
    location: 'Germany',
  },
  {
    main: 'Mist',
    description: 'mist',
    icon: '50d',
    temp: -0.61,
    feels_like: -5.45,
    temp_min: -1.36,
    temp_max: 0.88,
    location: 'Poland',
  },

  {
    main: 'Clear',
    description: 'clear sky',
    icon: '01d',
    temp: 0.96,
    feels_like: -3.46,
    temp_min: 0.15,
    temp_max: 2.22,
    location: 'England',
  },
  {
    main: 'Clouds',
    description: 'broken clouds',
    icon: '04d',
    temp: 13.92,
    feels_like: 12.86,
    temp_min: 13.44,
    temp_max: 14.78,
    location: 'Cañada',
  },
];
